apiVersion: v1
kind: Namespace
metadata:
  name: code-reader
  labels:
    name: code-reader
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: code-reader-test
  labels:
    name: code-reader-test
    environment: test
